"""empty message

Revision ID: 08336ae1630a
Revises: 16738667b432
Create Date: 2024-02-24 21:17:39.683028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08336ae1630a'
down_revision = '16738667b432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
